language: c
compiler: gcc

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y liblua5.2-dev

script: ./configure --enable-version --enable-symlink --enable-getaddrinfo --enable-lua --enable-atcp --enable-gmcp --enable-option102 && make
